name: shutoutschool
favicon: null
layout_spectrum: 0.50234
typography_spectrum: 0.58724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b7001d'
    - '#34a6d3'
    - '#c2515a'
    - '#8ac0d6'
  brandStrength: 0.5625
  lightness: 0.6728337216190994
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
